import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";

import "@/globals.css";

import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { NextAuthProvider } from "@/components/sections/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Troll with Fuhu",
  description: "Generated by pendev.cc",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <NextAuthProvider session={session}>
            <div className="relative flex flex-col">
              <Header />
              {children}
            </div>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
